"""ETL Plugins — backend-agnostic, orchestrator-agnostic Python ETL library.

See SPEC.md for the full design and ROADMAP.md for the implementation status.
"""

from etl_plugins.config import (
    ConnectionConfig,
    ConnectionsConfig,
    EnvSecretBackend,
    PipelineConfig,
    SecretBackend,
    SecretRef,
    StaticSecretBackend,
    expand_env,
    get_secret_backend,
    load_config,
    load_connections,
    load_dotenv,
    load_pipeline,
    load_yaml,
    resolve_secrets,
)
from etl_plugins.core import (
    BatchSink,
    BatchSource,
    ConfigError,
    ConnectError,
    Connector,
    ConnectorError,
    ConnectorRegistry,
    Context,
    ETLError,
    Field,
    Hook,
    Pipeline,
    PipelineError,
    ReadError,
    Record,
    RecordError,
    RegistryError,
    RunResult,
    Schema,
    SecretError,
    StreamSink,
    StreamSource,
    Task,
    TaskError,
    TransformError,
    TransformFn,
    WriteError,
)

__version__ = "0.0.1"

__all__ = [
    "BatchSink",
    "BatchSource",
    "ConfigError",
    "ConnectError",
    "ConnectionConfig",
    "ConnectionsConfig",
    "Connector",
    "ConnectorError",
    "ConnectorRegistry",
    "Context",
    "ETLError",
    "EnvSecretBackend",
    "Field",
    "Hook",
    "Pipeline",
    "PipelineConfig",
    "PipelineError",
    "ReadError",
    "Record",
    "RecordError",
    "RegistryError",
    "RunResult",
    "Schema",
    "SecretBackend",
    "SecretError",
    "SecretRef",
    "StaticSecretBackend",
    "StreamSink",
    "StreamSource",
    "Task",
    "TaskError",
    "TransformError",
    "TransformFn",
    "WriteError",
    "__version__",
    "expand_env",
    "get_secret_backend",
    "load_config",
    "load_connections",
    "load_dotenv",
    "load_pipeline",
    "load_yaml",
    "resolve_secrets",
]
