"""Observability: logging / metrics / tracing baselines. SPEC.md §9.2."""

from etl_plugins.observability.logging import (
    DEFAULT_SENSITIVE_KEYWORDS,
    MASK_VALUE,
    configure_logging,
    make_secret_masker,
    mask_sensitive_values,
)
from etl_plugins.observability.metrics import (
    DURATION_SECONDS,
    ERRORS_TOTAL,
    LAG_SECONDS,
    RECORDS_READ_TOTAL,
    RECORDS_WRITTEN_TOTAL,
    Attributes,
    Counter,
    Histogram,
    Metrics,
    NoOpCounter,
    NoOpHistogram,
    NoOpMetrics,
    get_metrics,
    reset_metrics,
    set_metrics,
)
from etl_plugins.observability.tracing import (
    NoOpSpan,
    NoOpTracer,
    Span,
    Tracer,
    get_tracer,
    reset_tracer,
    set_tracer,
)

__all__ = [
    "DEFAULT_SENSITIVE_KEYWORDS",
    "DURATION_SECONDS",
    "ERRORS_TOTAL",
    "LAG_SECONDS",
    "MASK_VALUE",
    "RECORDS_READ_TOTAL",
    "RECORDS_WRITTEN_TOTAL",
    "Attributes",
    "Counter",
    "Histogram",
    "Metrics",
    "NoOpCounter",
    "NoOpHistogram",
    "NoOpMetrics",
    "NoOpSpan",
    "NoOpTracer",
    "Span",
    "Tracer",
    "configure_logging",
    "get_metrics",
    "get_tracer",
    "make_secret_masker",
    "mask_sensitive_values",
    "reset_metrics",
    "reset_tracer",
    "set_metrics",
    "set_tracer",
]
