"""Application settings — single Pydantic class, env-driven.

Step 8.1. Replaces ad-hoc ``os.environ.get(...)`` reads. Extended in later
slices (auth keys in 8.2, OIDC config in 8.2, etc.).

Usage::

    from etlx_server.settings import Settings, get_settings

    settings = get_settings()          # cached, env-driven
    settings = Settings(database_url=...)  # explicit construction (tests)
"""

from __future__ import annotations

from enum import StrEnum
from functools import lru_cache

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Environment(StrEnum):
    """Deployment environment — drives a couple of safety defaults."""

    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class Settings(BaseSettings):
    """All server-side configuration.

    Loaded from the process environment (or ``.env`` if present). Field
    descriptions appear in the OpenAPI schema generated by FastAPI when these
    values surface in endpoints.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # --- service identity --------------------------------------------------
    service_name: str = Field(
        default="etlx-server",
        description="Reported on /version and emitted in logs.",
    )
    environment: Environment = Field(
        default=Environment.DEVELOPMENT,
        description="Drives safety defaults (e.g. /docs visibility).",
    )

    # --- database (ADR-0020) -----------------------------------------------
    database_url: str = Field(
        default="postgresql+asyncpg://etlx:etlx@localhost:5433/etlx",
        description="SQLAlchemy async URL for the metadata DB.",
    )
    database_echo: bool = Field(
        default=False,
        description="Log every SQL statement (dev only).",
    )

    # --- HTTP --------------------------------------------------------------
    cors_origins: list[str] = Field(
        default_factory=list,
        description="Allowed CORS origins. Empty disables CORS middleware.",
    )

    @property
    def docs_enabled(self) -> bool:
        """Hide /docs and /redoc in production by default."""
        return self.environment is not Environment.PRODUCTION


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Process-wide cached Settings instance.

    Tests that need to override values should construct ``Settings(...)``
    directly and pass it into ``create_app(settings=...)``.
    """
    return Settings()


__all__ = ["Environment", "Settings", "get_settings"]
