"""Application settings — single Pydantic class, env-driven.

Step 8.1. Replaces ad-hoc ``os.environ.get(...)`` reads. Extended in later
slices (auth keys in 8.2, OIDC config in 8.2, etc.).

Usage::

    from etlx_server.settings import Settings, get_settings

    settings = get_settings()          # cached, env-driven
    settings = Settings(database_url=...)  # explicit construction (tests)
"""

from __future__ import annotations

from enum import StrEnum
from functools import lru_cache

from pydantic import Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from etlx_server.auth.oidc_config import OidcProviderConfig


class Environment(StrEnum):
    """Deployment environment — drives a couple of safety defaults."""

    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class Settings(BaseSettings):
    """All server-side configuration.

    Loaded from the process environment (or ``.env`` if present). Field
    descriptions appear in the OpenAPI schema generated by FastAPI when these
    values surface in endpoints.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # --- service identity --------------------------------------------------
    service_name: str = Field(
        default="etlx-server",
        description="Reported on /version and emitted in logs.",
    )
    environment: Environment = Field(
        default=Environment.DEVELOPMENT,
        description="Drives safety defaults (e.g. /docs visibility).",
    )

    # --- database (ADR-0020) -----------------------------------------------
    database_url: str = Field(
        default="postgresql+asyncpg://etlx:etlx@localhost:5433/etlx",
        description="SQLAlchemy async URL for the metadata DB.",
    )
    database_echo: bool = Field(
        default=False,
        description="Log every SQL statement (dev only).",
    )

    # --- HTTP --------------------------------------------------------------
    cors_origins: list[str] = Field(
        default_factory=list,
        description="Allowed CORS origins. Empty disables CORS middleware.",
    )

    # --- auth (ADR-0023 — JWT RS256 + bcrypt local fallback) ---------------
    auth_jwt_private_key_pem: SecretStr | None = Field(
        default=None,
        description="RSA private key PEM (signing). Required to issue tokens.",
    )
    auth_jwt_public_key_pem: SecretStr | None = Field(
        default=None,
        description="RSA public key PEM (verification). Derived from private key if omitted.",
    )
    auth_jwt_issuer: str = Field(
        default="etlx-server",
        description="JWT 'iss' claim and validation expectation.",
    )
    auth_jwt_audience: str = Field(
        default="etlx",
        description="JWT 'aud' claim and validation expectation.",
    )
    auth_jwt_access_ttl_seconds: int = Field(
        default=900,
        description="Access token lifetime (default 15 min).",
    )
    auth_jwt_refresh_ttl_seconds: int = Field(
        default=86400 * 7,
        description="Refresh token lifetime (default 7 days).",
    )
    auth_local_enabled: bool = Field(
        default=True,
        description="If false, /auth/login (local email+password) returns 503.",
    )

    # --- OIDC (Step 8.2b, ADR-0023) ----------------------------------------
    auth_oidc_enabled: bool = Field(
        default=False,
        description="Master switch — when false, /auth/oidc/* returns 503 and "
        "the provider list is empty.",
    )
    auth_oidc_providers: list[OidcProviderConfig] = Field(
        default_factory=list,
        description="OIDC providers (Google / Azure AD / Okta / GitHub / "
        "custom). Provide via env as JSON (e.g. "
        '``AUTH_OIDC_PROVIDERS=\'[{"name":"google",...}]\'``).',
    )
    auth_oidc_state_ttl_seconds: int = Field(
        default=600,
        description="Lifetime of the signed state token that carries CSRF + "
        "nonce + return_to between /login and /callback (default 10 min).",
    )
    auth_oidc_http_timeout_seconds: float = Field(
        default=10.0,
        description="Timeout for outbound HTTP calls to the IdP (discovery, "
        "JWKS, token endpoint, userinfo).",
    )

    @property
    def docs_enabled(self) -> bool:
        """Hide /docs and /redoc in production by default."""
        return self.environment is not Environment.PRODUCTION


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Process-wide cached Settings instance.

    Tests that need to override values should construct ``Settings(...)``
    directly and pass it into ``create_app(settings=...)``.
    """
    return Settings()


__all__ = ["Environment", "Settings", "get_settings"]
